import type { Metadata } from "next";
import "@radix-ui/themes/styles.css";
import { Open_Sans } from "next/font/google";
import "./globals.css";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "KraftKollectors",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` bg-light text-black-800 text-body`}>{children}</body>
    </html>
  );
}
