import type { Metadata } from "next";
import "@radix-ui/themes/styles.css";
import "@/assets/globals.css";
import "@/assets/fonts.css";
import { Theme } from "@radix-ui/themes";
import AuthProvider from "@/components/server/AuthProvider";
import { Suspense } from "react";


export const metadata: Metadata = {
  title: "KraftKollectors",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <Suspense>
        <AuthProvider />
      </Suspense>
      <body className={` bg-light text-black-800 text-body font-normal`}>
        <Theme>
          {children}
          </Theme>
      </body>
    </html>
  );
}
